print("=" * 40)
print("🐍 CHÀO MỪNG ĐẾN VỚI PYTHON! 🐍")
print("=" * 40)
print()
print("👋 Xin chào! Tôi là Python!")
print("🎯 Tôi sẽ giúp bạn học lập trình!")
print("🚀 Chúng ta sẽ tạo ra những điều tuyệt vời!")
print("💡 Bắt đầu hành trình thú vị nào!")
print()
print("=" * 40)
print("🎉 CHƯƠNG TRÌNH ĐẦU TIÊN THÀNH CÔNG! 🎉")
print("=" * 40)
